<?php
/**
 * Test class for Customer.
 * Generated by PHPUnit on 2012-05-10 at 13:56:09.
 */
class CustomerTest extends CTestCase
{
    /**
     * @var Customer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Customer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        /*$this->markTestIncomplete(
          'This test has not been implemented yet.'
        );*/
        $customer = new Customer();
        $this->assertFalse($customer->validate());
    }

    /**
     * @todo Implement testRelations().
     */
    public function testRelations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAttributeLabels().
     */
    public function testAttributeLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
