<?php

require_once 'C:\webroot\airmate\protected\models\lottery_draw\LotteryDraw.php';

/**
 * Test class for LotteryDraw.
 * Generated by PHPUnit on 2012-05-07 at 05:47:46.
 */
class LotteryDrawTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var LotteryDraw
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new LotteryDraw;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDoIt().
     */
    public function testDoIt()
    {
        // Remove the following lines when you implement this test.
        /*$this->markTestIncomplete(
          'This test has not been implemented yet.'
        );*/
        $numCard = '0d5d083adc7f45';
        $numProduct = 'FT36T2';
        $numFlow = '000939100925E41';

        // test preg_split
        $arrNumCard = preg_split('//', $numCard, -1, PREG_SPLIT_NO_EMPTY);
        $this->assertEquals(strlen($numCard), count($arrNumCard));

        $lotteryDraw = new LotteryDraw($numCard, $numProduct, $numFlow);
        $lotteryDraw->setQuantity(5);
        $lotteryDraw->setTimes(1);
//         echo $lotteryDraw->doIt();
        $success = 0;
        $failure = 0;
        $max = 1000;
        for($i = 0; $i < $max; $i++)
        {
            $number = $lotteryDraw->doIt();
            $this->assertTrue(is_int($number));
            if(1 <= $number && 500 >= $number)
            {
                $success++;
            }
            else
            {
                $failure++;
            }
        }
        echo "success: {$success}\nfailure: {$failure}";
    }
}
?>
